### ISSUE TITLE
Bugfix release raises new errors

### ISSUE THREAD

**Issue by no-reply** [voormedia/flipflop#26]
Today's release of v2.3.2 introduces [new explict raises](
https://github.com/voormedia/flipflop/commit/a6e639c6c631cdb5e74cb84a1a2a314ca3420579#diff-4a9118dd30473e82437e25fedbbe8814R94) to public method signatures. This is causing breaking builds on downstream dependencies with

```
Flipflop::FeatureError:
  Feature '123' unknown.
```

In my case, this only seems to be impacting tests that explicitly pass dummy data to `FlipFlop` methods, but I thought I'd report it as an unexpected breakage.

Perhaps 2.3.2 could have been 2.4.0 (or 3.0.0)?

**Comment by mjgiarlo** [comment]
This is the line that fails: https://github.com/samvera/hyrax/blob/master/spec/controllers/hyrax/admin/strategies_controller_spec.rb#L23. I'm not ruling out the possibility that Hyrax is testing things wrong.

**Comment by rolftimmermans** [comment]
Thanks for the report. I agree that this is unfortunate although the change is intentional. 2.3.2 is out the door now so I'm not sure it's an improvement to release a new version, but at least I'll add it to the release notes.

We'll try to be more careful releasing breaking changes in the future, and make sure they get a major or minor release.

**Comment by rolftimmermans** [comment]
On second thought I'll remove 2.3.2 and release 2.4.0 immediately.
