### ISSUE TITLE
Access to Flipflop in initializer ?

### ISSUE THREAD

**Issue by Keirua** [voormedia/flipflop#31]
Hi !

First, congrats for this great library, it's super nice and very useful to us.
We wanted to add a feature and use it in an initializer (our use case: to be able to toggle `Rails.application.config.content_security_policy_report_only` without doing a deployment, because content-security-policy headers are error-prone and we may need to quickly disable them, despite extensive tests)

It seem not to be possible, because of the boot order: `config/features.rb` is loaded after anything in `config/initializers` (or `config/environments`). Did I understand the problem correctly ? Is there any chance to be able to use Flipflop during the initialization ?

Thanks !

**Comment by rolftimmermans** [comment]
Checking for features during initialisation is not possible because there is no mechanism to forcefully restart and reinitialise Rails when toggling a feature (at least not currently). I imagine you have two options:

1) Hardcode the value in your initialisation config file and redeploy when you make a change
2) Overwrite the relevant Rails methods with something that does a dynamic check for a feature (requiring no change to Flipflop, just a redefinition of a particular Rails method)

Does that help?

**Comment by Keirua** [comment]
Thanks for this quick and detailed answer. It does help! Even though we'll settle for the simpler option 1), I had not thought about option 2) which is a great way to do that.
